### ISSUE TITLE
fix variables in '@baloise/design-system-css/scss/mixins/breakpoint.mixin.sass'

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#935]
## Detailed description

The file makes use of variables like '$tablet' which seem not to exist anymore. E.g.:

```
=tablet
  @media screen and (min-width: $tablet), print
    @content

```

> What did you expect to happen? What happened instead? What would you like to see changed?

`$tablet` should be replace with `$bal-tablet`. Applies to all variables.

**Comment by hirsch88** [comment]
@svene which version you are using?

**Comment by hirsch88** [comment]
the $tablet var gets imported from `@import '@baloise/design-system-tokens/dist/tokens.legacy.sass'`

**Comment by hirsch88** [comment]
```scss
@import "@baloise/design-system-components/src/styles/global.utilities";

@include tablet() {
  .my-custom-style {
    background: lime !important;
  }
}
```
